0.3.1/config/routes.rb
Obri::Application.routes.draw do 
  devise_for :users do
  	match 'user' => "papers#index", :as => :user_root
  end
  resources :users

  get "home/index"

  resource :instructions do
    collection do
      get "index"
      get 'authorship'
      get "instruction_for_online_submission"
      get "instruction_for_author"
      get "rules_of_edit"
      get "procedure"
    end
  end
  
  resources :papers do
    collection do
      get 'all_paper'
      get 'review'
      get "filtered_for_editor"
      get 'authorship'
      get 'completed_paper'
    end
    member do
      get "make_comment"
      get 'confirm_submission'
      get "change_status"
      get 'result'
    end
  end
  
  resources :roles do
    collection do
      get "modify_role"
      get "all_user"
      get "manage_role"
      get "assignment"
    end
    member do
      get "change_role"
      get "make_assignment"
    end
  end

  
  root :to => "home#index"
  

  namespace :user do
    root :to => "home#index"
    resources :papers
    resources :papers do
      collection do
        get 'all_paper'
        get 'authorship'
        get 'review'
        get "filtered_for_editor"
        get 'completed_paper'
      end
      member do
        get "make_comment"
        get 'confirm_submission'
        get "change_status"
        get 'result'
      end
    end
    
    resources :roles do
      collection do
        get "modify_role"
        get "all_user"
        get "manage_role"
        get "assignment"
      end
      member do
        get "change_role"
        get "make_assignment"
      end
    end
        
        

    
  end
  

  

  

end

0.3.1/app/models/paper.rb
class Paper < ActiveRecord::Base
  # paper의 소유자는 user
  belongs_to :user
  
  # validation 체크와 ->ㅇ 보완 필요 
  validates :first_name,  :presence => true
  validates :last_name,  :presence => true
  validates :postal_address,  :presence => true
  validates :postal_code,  :presence => true
  validates :nation,  :presence => true
  validates :phone,  :presence => true
  #validates :fax
  
  validates :email,  :presence => true
  validates_format_of :email,
                      :with =>  /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i,
                      :message => "Its not a valid format"
                      
  validates :title,  :presence => true, :length => { :minimum => 5 }
  # integer
  validates :number_of_authors,  :presence => true
  #text                  
  validates :names_of_authors,  :presence => true
  validates :emails_of_authors,  :presence => true
  
  validates :abstract,  :presence => true
  validates :types,  :presence => true
  validates :section,  :presence => true

  # Coveletter
  has_attached_file :coverletter
  
  # PDFs
  has_attached_file :manuscript
   
  # supplemental files
  # 다수 그림 파일 처리.
  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets, :allow_destroy => true
  
  # 선택지 설정.
  STATUS  = ['On editing','Submitted', 'On chief editor', 'Peer review','Peer review(Revision)','On chief reviewer','On chief reviewer(Revision)','Revision','Rejected','Accepted']
  
  TYPES = %w[Article Review Case_report Note]
  
  SECTIONS  =['Human Biology', 'Oral Anatomy','Oral Physiology','Oral Biochemistry','Oral Microbiology','Oral Histology',
              'Dental Materials','Dental Pharmacology','Oral and maxillofacial pathology','Oral Medicine',
              'Oral and Maxillofacial Radiology','Preventive and Public Health Dentistry','Oral Conservative Dentistry',
              'Pediatric Dentistry','Periodontology','Oral and Maxillofacial Surgery','Prosthodontics','Orthodontics']
  
  COUNTRYS = %w[ Korea,_Republic_of_(South_Korea)
  
    AFGHANISTAN ALBANIA ALGERIA AMERICAN_SAMOA ANDORRA ANGOLA ANGUILLA ANTARCTICA ARGENTINA ARMENIA ARUBA 
                 AUSTRALIA AUSTRIA AZERBAIJAN BAHAMAS BAHRAIN BANGLADESH BARBADOS BELARUS BELGIUM BELIZE BENIN BERMUDA BHUTAN BOLIVIA
                 BOSNIA_AND_HERZEGOVINA BOTSWANA BOUVET ISLAND BRAZIL BRUNEI BULGARIA BURUNDI CAMBODIA CAMEROON CANADA 
                 CAYMAN_ISLANDS CENTRAL_AFRICAN_REPUBLIC  CHAD CHILE CHINA CHRISTMAS_ISLAND COLOMBIA COMOROS CONGO COOK_ISLANDS 
                 COSTARICA COTE_D'IVOIRE CROATIA CUBA CURACAO CYPRUS CZECH_REPUBLIC DENMARK DJIBOUTI DOMINICA DOMINICAN_REPUBLIC   
               	ECUADOR EGYPT EL_SALVADOR ERITREA ESTONIA ETHIOPIA FRANCE GABON GAMBIA GEORGIA GERMANY GHANA GIBRALTAR GREECE 
               	GREENLAND GRENADA GUADELOUPE GUAM GUATEMALA GUERNSEY GUINEA GUINEA-BISSAU GUYANA HOLY_SEE HONDURAS HONGKONG HUNGARY
               	ICELAND INDIA INDONESIA IRAN IRAQ IRELAND ISRAEL ITALYJAMAICA JAPAN JERSEY JORDAN   
               	KAZAKHSTAN KENYA 
               	Korea,_Democratic_People's_Republic_of_(North_Korea)
               	KUWAIT KYRGYZSTAN   
               	LATVIA LEBANON LIBERIA JAMAHIRIYA LIECHTENSTEIN LITHUANIA LUXEMBOURG   
               	MALAYSIA MALDIVES MALI MALTA MEXICO MONACO MONGOLIA MONTENEGRO MONTSERRAT MOROCCO MOZAMBIQUE MYANMAR   
               	NEPAL NETHERLANDS NEW_CALEDONIA NEW_ZEALAND NICARAGUA NIGERIA NORWAY OMAN   
               			 PAKISTAN PANAMA PAPUA_NEW_GUINEA PARAGUAY PERU PHILIPPINES POLAND PORTUGAL PUERTO_RICO QATAR   
               		 ROMANIA RUSSIAN_FEDERATION RWANDA   
               			  SAMOA SAUDI_ARABIA SENEGAL SERBIA SINGAPORE SLOVAKIA SOUTH_AFRICA SPAIN SRI_LANKA SUDAN 
               			  SWAZILAND SWEDEN SWITZERLAND TAIWAN THAILAND TUNISIA TURKEY   
              UGANDA ARAB_EMIRATES UNITED_KINGDOM UNITED_STATES_OF_AMERICA URUGUAY UZBEKISTAN VENEZUELA YEMEN ZAMBIA ZIMBABWE


                 ]  
end

0.3.1/app/controllers/papers_controller.rb
class PapersController < ApplicationController
  # cancan 인증 작업. 각 작업에 대해서 인증된사 사람만이 접근. 자신의 논문만 제어하는 것은 ability.rb에서 처리. 
  load_and_authorize_resource
  
  # 로그인 하지 않으면 볼수 없음. 특정 페이지로 바로 이동하면 이로그인 화면이 뜬다. 
  before_filter :authenticate_user!
  #before_filter :authenticate_user!, :except => [:show, :index]
  
  # GET /papers
  # GET /papers.xml
  def index
    # cancan 인증으로 필요 없음.
    # 모든 사용장의 논문을 보여준다.
    #@papers = Paper.all
    
    #현재 사용자의 논문만 보여준다. 
    @papers = current_user.papers.all
      
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @papers }
    end
  end
  
  # GET /papers/1
  # GET /papers/1.xml
  def show
    # cancan 인증으로 필요 없음.
    #@paper = Paper.find(params[:id])
   
    # 어드민이나 에디터의 코멘트 처리를 위해 필요.
    if current_user.role.eql?("Administrator") or current_user.role.eql?("Chiefeditor") 
      @comments = { @paper.examiner1 => [@paper.examiner_name1.split(".")[1].lstrip, @paper.comment1], @paper.examiner2 => [@paper.examiner_name2.split(".")[1].lstrip, @paper.comment2], @paper.examiner3 => [@paper.examiner_name3.split(".")[1].lstrip, @paper.comment3]}
    elsif current_user.role.eql?("Reviewer")               
      # 심사위원이 남긴콭멘트 내가 마긴 코멘트이다. 
      @my_comment = filter_for_review(@paper, current_user)
    end
    

    ################ TEST ##################
    #@paper.examiner_name1 = "4. 심사위원"
    #@paper.examiner_name2 = "8. 심사위원2"
    #@paper.examiner_name3 = "6. Bean"
    
    #@paper.examiner1 = "examiner@g.com"
    #@paper.examiner2 = "examiner2@g.com"
    #@paper.examiner3 = "jinwoojiji@gmail.com"
    
    #@paper.comment1 = ""
    #@paper.comment2 = ""
    #@paper.comment3 = ""
    
    #@paper.status = 'Peer review'
    #@paper.save
    ############### TEST ###################
    
    
    # 다른 방법 접근 예를 들어. localhost:3000/papers/13 시으로 숫자를 바로 입력 하
    # Reviewer는 접근이 가능 하니 문제가 있음. Reviewer는 읽는것은 모든게 가능.
    # 그래서런 이런 접근을 막기 위해서 examiner 의 접근을 자기가 가진 것과 리뷰 할 수 있는 것만 으로 제한. 
    # 이 제한은 위와 같인 임의로 접근 하는 것을 위한 것이고 다른 곳에서는 이미 구비되어 있음.
    # 다른 곳에서는 index에서 이미 필터하여 보이지가 않음. 
    if current_user.role.eql?('Reviewer')
      unless current_user.papers.include?(@paper) 
        flash[:error] = "Access denied!"  
        #redirect_to root_url
      end
      unless filter_for_review(@paper, current_user)
        flash[:error] = "Access denied!"  
        #redirect_to root_url
      end
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.xml
  def new
    # cancan 인증으로 필요 없음.
    #@paper = Paper.new
    # 부가파일 갯수 정의. 5개 까지 정의 하고 업로드으 되었을 경우 그 수만큼 빼고 보여줌.  
    (10 - @paper.assets.length).times { @paper.assets.build }

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    # cancan 인증으로 필요 없음.
    #@paper = Paper.find(params[:id])
    # 수정시 시간 변경.
    t = Time.new
    @paper.receive_time = t.strftime("%Y-%m-%d %H:%M")
    
   # (5 - @paper.assets.length).times { @paper.assets.build }
  end

  # POST /papers
  # POST /papers.xml
  def create
    ##########################################################################################
    # paper와 user 연동을 위해 필수 적인곳. 하위 개념인 paper에 상위 개념에 해당하는 user의 user_id의 integer 형을 만들어 주어야
    # cancan 인증에서도 이건 필요함. 
    ##########################################################################################
    @paper = current_user.papers.build(params[:paper])

    ################ Initial value ##################
    @paper.status = 'On editing'
    t = Time.new
    @paper.receive_time = t.strftime("%Y-%m-%d %H:%M:%S")
    @paper.nation = 'Korea'
    
    @paper.examiner_name1 = "0. Not yet assigned"
    @paper.examiner_name2 = "0. Not yet assigned"
    @paper.examiner_name3 = "0. Not yet assigned"
    
    @paper.examiner1 = "Not yet"
    @paper.examiner2 = "Not yet"
    @paper.examiner3 = "Not yet"
    
    @paper.comment1 = "Not yet"
    @paper.comment2 = "Not yet"
    @paper.comment3 = "Not yet"
  
    ################ Initial value ##################
    
    
    respond_to do |format|
      if @paper.save
        format.html { redirect_to(@paper, :notice => 'The new submission was successfully created.') }
        format.xml  { render :xml => @paper, :status => :created, :location => @paper }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.xml
  def update
    # cancan 인증으로 필요 없음.
    #@paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to(@paper, :notice => 'The submission was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @paper.errors, :status => :unprocessable_entity }
      end
    end  
  end

  # DELETE /papers/1
  # DELETE /papers/1.xml
  def destroy
    # cancan 인증으로 필요 없음.
    #@paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to(papers_url) }
      format.xml  { head :ok }
    end
  end
  
  ########################  ########################  ########################  ########################
  ### 추가 함수 
  ########################  ########################  ########################  ########################
  
  # term& condition을 보여줌.
  def authorship
  end
  
  ##################################################################################  
  # 상태 변경 함수. 주로 view에서 컨트롤러 쪽으로 읽어오는게 많다. 
  ##################################################################################
  
  # status change. 어드민이 인위적으로 status 변경.
  def change_status
    @paper = Paper.find(params[:id])
    @paper.status = params[:status]
    @paper.save

    respond_to do |format|
      if @paper.update_attributes(params[:id])
        if current_user.role.eql?('Administrator')
      	  format.html { redirect_to(all_paper_papers_path, :notice => 'You changed the status of paper : '+ @paper.title) }
        else
          format.html { redirect_to(filtered_for_editor_papers_path, :notice => 'You changed the status of paper : '+ @paper.title) }
        end
      else
        if current_user.role.eql?('Administrator')
          format.html { redirect_to(all_paper_papers_path, :notice => 'You got an error, please retry.')}
        else
          format.html { redirect_to(filtered_for_editor_papers_path, :notice => 'You got an error, please retry.')}
        end
      end
    end
    
  end
  
  # 투고자의  컨펌 함수 
  def confirm_submission
    @paper = Paper.find(params[:id])
    @editors = get_editors
    
    if @paper.status == 'On editing'
      @paper.status = 'Submitted'
      @paper.save
      # 컨펌시에는 메인에디터에게만 메일 보냄.
    
    # revision일경우엔 바로 peer review로 넘어간다. 이미 심사위원은 정해짐.      
    elsif  @paper.status == 'Revision'
      @paper.status = 'Peer review(Revision)'
      @paper.comment1 = "Not yet"
      @paper.comment2 = "Not yet"
      @paper.comment3 = "Not yet"
      @paper.result = "Not yet"
      @paper.save
      
      title = 'OBRI ## The revised paper comes to you : ' + @paper.title
      #리 리뷰어들에게 메일 보내는거 추가. 지점장과 작가 에게도.
      Emailer.send_paper(@paper,  title, @paper.examiner1).deliver
      Emailer.send_paper(@paper,  title, @paper.examiner2).deliver
      Emailer.send_paper(@paper,  title, @paper.examiner3).deliver      
    else
    end
    
    @editors.each do |editor|
      Emailer.send_new_paper(@paper,editor.email).deliver
    end
    
    Emailer.send_receipt(@paper).deliver
   
   respond_to do |format|
     if @paper.update_attributes(params[:id])
       format.html { redirect_to(papers_path, :notice => 'You have submitted the paper : '+ @paper.title) }
     else
       format.html { redirect_to(papers_path, :notice => 'You got an error, please retry.')}
     end
   end
    
  end
  
  
  # 리절트 치는 함수 에디터가.
  def result
    @paper = Paper.find(params[:id])
    
    # accept 결정. 
    if params[:yn] == "1"
      @paper.status = "Accepted"
    elsif params[:yn] == "0"
      @paper.status = "Revision"
    elsif params[:yn] == "-1"
      @paper.status = "Rejected"
    else
      redirect_to(papers_path, :notice => 'You got an error, please retry.')
    end
    
    # final result 저장.
    @paper.result = params[:result]
    
    @paper.save
    
    Emailer.send_result(@paper).deliver

    respond_to do |format|
      if @paper.update_attributes(params[:id])
        format.html { redirect_to(filtered_for_editor_papers_path, :notice => 'Sent the resulf of the paper : '+ @paper.title) }
      else
        format.html { redirect_to(filtered_for_editor_papers_path, :notice => 'You got an error, please retry.')}
      end
    end
    
    
  end
  
  
  # 심사위원이 코멘트 치는 함수 
  def make_comment
    @paper = Paper.find(params[:id])
    title = @paper.title
    @editors = get_editors
        
    # E-mail 주석 모두 제거.
    if current_user.email.eql?(@paper.examiner1) 
      @paper.comment1 = params[:comment]
    elsif current_user.email.eql?(@paper.examiner2) 
      @paper.comment2 = params[:comment]
    elsif current_user.email.eql?(@paper.examiner3) 
      @paper.comment3 = params[:comment]
    else
      redirect_to(review_papers_path, :notice => 'You got an error')
    end
    
    @editors.each do |editor|
      Emailer.send_info_to_role(@paper, params[:comment],'OBRI ## A new comment on "' + title+ '"',editor.email,current_user.name).deliver
    end
        
    if @paper.comment1 != "Not yet" and @paper.comment2 != "Not yet" and @paper.comment3 != "Not yet"
      if @paper.status == 'Peer review(Revision)'
        @paper.status = 'On chief reviewer(Revision)'
      else
        @paper.status = "On chief reviewer"
      end
      

0.3.1/app/views/papers/.PREVIEW-index.html.erb
<h1>My manuscripts</h1>
<label>Your email: </label> <%= current_user.email %><br>
<label>Number of submitted manuscripts: </label> <%= current_user.papers.size %><br>
<label>Your role:</label> <%= current_user.role %><br>

<br>

<table>
  <tbody><tr>
    <th>Title</th>
	<th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>   
	<th>Received time</th>
	<th>Status</th>
	<th>Download manuscript </th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @papers.each do |paper| %>
  <tr>
	<td><%= paper.title %></td>
    <td><%= paper.first_name %></td>
    <td><%= paper.last_name %></td>
    <td><%= paper.email %></td>   
	<td><%= paper.receive_time %></td>
	<td><%= paper.status %></td>  
	<td><%= link_to "Download", paper.manuscript.url %></td> 
    <td><%= link_to 'Show', paper %></td>
    <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
    <td><%= link_to 'Delete', paper, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</tbody></table>

<br>

<%= link_to 'New submission', controller => "papers", :action => "authorship"  %>

<% #투고자를 제외한 모든 사람은 모든 노문을수 볼 수 있음.  %>

<% unless current_user.role == 'author'%>
	<%= link_to "See all author's submitted manuscripts", :controller => "papers", :action => "all_papers" %>
<% end %>

0.3.1/app/views/papers/authorship.html.erb
<h1>Authorship agreement</h1>
<blockquote>
<p>
	1. None of the material in the manuscript is included in another manuscript, has been published previously, or is currently under consideration for publication elsewhere. 
</p><p><br>
	2. All authors listed on the manuscript have contributed significantly to the conception and design of experimental studies or the analysis and interpretation of data. 
</p><p><br>
	3. All authors understand the contents of the manuscript, and have approved its submission.
</p><p><br>
	4. All authors must disclose any commercial association that might pose a conflict of interest in connection with the manuscript. Research or project support should be acknowledged.
</p><p><br>
	5. When a manuscript is accepted for publication, copyright ownership is transferred to the Oral Biology Research Institute.
</p>
</blockquote>

<h4>
	<div align="center">
		<%= link_to "I don't agree", papers_path %> |
		<%= link_to 'I agree', new_paper_path %>
	</div>
</h4>

0.3.1/app/views/papers/completed_paper.html.erb
<h1>Completed manuscripts</h1>
<ul>
<li>Your email :  <%= current_user.email %></li>
<li>Your role : <%= current_user.role %></li>
</ul>
</br>


<% @papers.each do |paper| %>
<table  CELLSPACING="10" CELLPADDING="3" style="table-layout:fixed;" >
  <h3><tr>
	<th width="400px" >Title</th>
	<th width="50px" >Name</th>
	<th width="100px" >Received</th>
	<th width="150px" >Status</th>	 
	<th width="80px ">Manuscript</th>	
	<th></th>	
  </tr></h3>

  <tr>
	<td width="300px" style="word-break:break-all;"><%= paper.title %></td>
    <td><%= paper.last_name %><%= paper.first_name %></td>
	<td><%= paper.receive_time.strftime("%Y-%m-%d") %></td>
	<td><%= paper.status %></td>  
	<td><%= link_to "Download", paper.manuscript.url %></td> 
	<td><%= link_to 'Show',paper %></td>

  </tr>
</table>
	<p>
	<h4>Result </h4>
	</p>
		<ul><blockquote>
		<%= paper.result %>
		</blockquote></ul><br><br>
<% end %>

0.3.1/app/views/papers/filtered_for_editor.html.erb
<h1>All manuscripts</h1>
<ul>
<li>Your email :  <%= current_user.email %></li>
<li>Your role : <%= current_user.role %></li>
<li>After Peer review, you can see "Result" area. </li>
<li>In Result area, you have to choose some result and type final comment. It will be sent to author by e-mail. </li>
<li>Clicking "Send the result" link will take a couple of seconds, because it sends some mails.</li>
<li>Click "Assign reviewer" link to assign reviewers </li> 
</ul>
</br>


<% @papers.each do |paper| %>
<table  CELLSPACING="10" CELLPADDING="3" style="table-layout:fixed;" >
  <h3><tr>
	<th width="400px" >Title</th>
	<th width="50px" >Name</th>
	<th width="100px" >Received</th>
	<th width="150px" >Status</th>	 
	<th width="80px">Manuscript</th>	
	<th></th>	
  </tr></h3>

  <tr>
	<td width="300px" style="word-break:break-all;"><%= paper.title %></td>
    <td><%= paper.last_name %><%= paper.first_name %></td>
	<td><%= paper.receive_time.strftime("%Y-%m-%d") %></td>
	<td><%= paper.status %></td>  
	<td><%= link_to "Download", paper.manuscript.url %></td> 
	<td><%= link_to 'Show',paper %></td>	
  </tr>
</table>

	<% if current_user.role.eql?('Chiefeditor') %>
		<% if paper.status == "On chief reviewer" or paper.status == "On chief reviewer(Revision)" %>
		   	<% @comments = { paper.examiner1 => [paper.examiner_name1.split(".")[1].lstrip, paper.comment1], paper.examiner2 => [paper.examiner_name2.split(".")[1].lstrip, paper.comment2], paper.examiner3 => [paper.examiner_name3.split(".")[1].lstrip, paper.comment3]} %>
			<p>
			<h4> Comments </h4>
			</p>
			<% @comments.each do |examiner, comment| %>
				<p>
				<b> <%= comment[0] %> </b><br>
			  	<ul><blockquote>
				<%= comment[1] %>		
				</blockquote>
				</ul>
				</p>
			<% end %>
	
			</br>
			<p>
			<h4>Result </h4>
			</p>

			<% # dynamic_form 이 필요. %>
			<% ########################################################################################### %>
			<% # 정말 이지 가장 중요한 파트이다.%>
			<% # 일단 remote 일 경우 params 해쉬로 접근이 가능 핟. %>
			<% # get, put, post 도 구별.ㅂ포스트는 새로 만드는 create 이다 . rake routes 해보면 알수 있다. %>
			<% # id 는 memeber와 collection의 차이아다. id도 params의 일부가 왼다. route.rb 참조. %>
			<% # 다른 방법은 잘안된다. form_tag나 form_for 로 submit_tag나 f.submit 만이 remote가 가능 하다.%>
			<% # tag 사용 법에 유의, 처음이 id 두번째가 value값(기본 내용), 세번째부터 옵션이다. %>
			<% # remote => ture 때니 모든 파라미터 접근 가능. 이게 무슨 일인가.. %>
			<% ########################################################################################### %>
			<%= form_tag({:controller => "papers", :action => "result", :id => paper}, :method => "get") do  %>
				<p>
				<div align="center">	
				Accepted <%= radio_button_tag(:yn, value = "1")%>
				Revision <%= radio_button_tag(:yn, value = "0")%>
				Rejected <%= radio_button_tag(:yn, value = "-1", checked = true)%>
				<br><br>
				<b> Final comment :</b>		
				<%= text_area_tag(:result,"" , :size =>"90x5") %><br><br>
				<%= submit_tag "Send the result", :confirm => "Are you sure?" %>
				</div>
				</p>
			<% end %>


		<% else %>
		<% end %>
	<% end %>
<br>	
<% end %>
<br>
<h4>
 <%= link_to 'Assign reviewer', assignment_roles_path %></h4>

0.3.1/app/views/papers/index.html.erb
<h1>My manuscripts</h1>

<ul>
<li>Your email :  <%= current_user.email %></li>
<li>Number of submitted papers :  <%= current_user.papers.size %></li>
<li>Your role : <%= current_user.role %></li>
<li>After submitted, you can't change or delete your submitted manuscript and information</li>
<li>Clicking "Submit" link will take a couple of seconds, because it sends some mails.</li> 
</ul>
</br>

<table height ="50px" CELLSPACING="10" CELLPADDING="5" style="table-layout:fixed;">
  <h3><tr>
	
    <th width="400px" >Title</th>
	<th width="100px" >Submitted</th>
	<th width="150px" >Status</th>
	<th width="100px">Manuscript</th>
	
	<th ></th>
	<th ></th>
	<th ></th>
	<th ></th>
  </tr></h3>

<% @papers.each do |paper| %>
  <tr>
	<td style="word-break:break-all;"><%= paper.title %></td>
	<td text-align="center"><%= paper.receive_time.strftime("%Y-%m-%d")%></td>
	<td><%= paper.status %></td>  
	<td><%= link_to "Download", paper.manuscript.url %></td> 
	<td><%= link_to 'Show', paper %></td>
	<% if paper.status.eql?('On editing')%>
		<td><%= link_to 'Edit', edit_paper_path(paper) %></td>
    	<td><%= link_to 'Delete', paper, :confirm => 'Are you sure?', :method => :delete %></td>
		<td><%= link_to 'Submit',:confirm => 'Are you sure?', :controller => 'papers', :action =>"confirm_submission", :id => paper %></td>
	<% elsif paper.status.eql?('Revision')%>
		<td><%= link_to 'Edit', edit_paper_path(paper) %></td>
		<td><%= link_to 'Resubmit',:confirm => 'Are you sure?', :controller => 'papers', :action =>"confirm_submission", :id => paper 
%></td>
		<td></td>
	<% else%>
		<td></td> <td></td> <td></td>
	<% end %>
  </tr>
<% end %>
</table>

<br />

<h4>
<%= link_to 'New submission', authorship_papers_path %>
</h4>