0.3.1/config/routes.rb
Obri::Application.routes.draw do 
  devise_for :users do
  	match 'user' => "papers#index", :as => :user_root
  end
  resources :users

  get "home/index"

  resource :instructions do
    collection do
      get "index"
      get 'authorship'
      get "instruction_for_online_submission"
      get "instruction_for_author"
      get "rules_of_edit"
      get "procedure"
    end
  end
  
  resources :papers do
    collection do
      get 'all_paper'
      get 'review'
      get "filtered_for_editor"
      get 'authorship'
      get 'completed_paper'
    end
    member do
      get "make_comment"
      get 'confirm_submission'
      get "change_status"
      get 'result'
    end
  end
  
  resources :roles do
    collection do
      get "modify_role"
      get "all_user"
      get "manage_role"
      get "assignment"
    end
    member do
      get "change_role"
      get "make_assignment"
    end
  end

  
  root :to => "home#index"
  

  namespace :user do
    root :to => "home#index"
    resources :papers
    resources :papers do
      collection do
        get 'all_paper'
        get 'authorship'
        get 'review'
        get "filtered_for_editor"
        get 'completed_paper'
      end
      member do
        get "make_comment"
        get 'confirm_submission'
        get "change_status"
        get 'result'
      end
    end
    
    resources :roles do
      collection do
        get "modify_role"
        get "all_user"
        get "manage_role"
        get "assignment"
      end
      member do
        get "change_role"
        get "make_assignment"
      end
    end
        
        

    
  end
  

  

  

end

0.3.1/app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  def index
  end
  
  def instruction_for_online_submission
  end
  
  def instruction_for_author
  end
  
  def rules_of_edit
  end
  
  def procedure
  end
  
  def authorship
  end

end

0.3.1/app/views/instructions/Instruction_for_author.html.erb
<h1> Instruction for author </h1>
<blockquote>
	<p>Etiam vehicula, augue eu ultricies dictum, orci nisi suscipit sem, nec sollicitudin neque est ac massa. Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat. Nulla lobortis bibendum magna. Nulla adipiscing justo eu erat.</p>
	<p>Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat.</p>
</blockquote>

0.3.1/app/views/instructions/Instruction_for_online_submission.html.erb
<h1> Instruction for online submission </h1>
<blockquote>
	<p>Etiam vehicula, augue eu ultricies dictum, orci nisi suscipit sem, nec sollicitudin neque est ac massa. Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat. Nulla lobortis bibendum magna. Nulla adipiscing justo eu erat.</p>
	<p>Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat.</p>
</blockquote>

0.3.1/app/views/instructions/authorship.html.erb
<h1>Authorship agreement</h1>
<blockquote>
	<p>Etiam vehicula, augue eu ultricies dictum, orci nisi suscipit sem, nec sollicitudin neque est ac massa. Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat. Nulla lobortis bibendum magna. Nulla adipiscing justo eu erat.</p>
	<p>Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat.</p>
</blockquote>

0.3.1/app/views/instructions/index.html.erb
<h1>Instruction</h1>

<ul>
<li><%= link_to 'Instruction for online submission', instruction_for_online_submission_instructions_path %></li>
<li><%= link_to 'Instruction for author', instruction_for_author_instructions_path %></li>
<li><%= link_to 'Rules of edit', rules_of_edit_instructions_path%></li>
<li><%= link_to 'Procedure of examination and publication', procedure_instructions_path %></li>
<li><%= link_to 'Authorship agreement', authorship_instructions_path%></li>

</ul>

0.3.1/app/views/instructions/instruction.html.erb
<h1>Instruction</h1>
<blockquote>
	<p>Etiam vehicula, augue eu ultricies dictum, orci nisi suscipit sem, nec sollicitudin neque est ac massa. Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat. Nulla lobortis bibendum magna. Nulla adipiscing justo eu erat.</p>
	<p>Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat.</p>
</blockquote>
<ul>
<li><%= link_to 'Instruction for online submission', :controller => "pages", :action => 'instruction_for_online_submission' %></li>
<li><%= link_to 'Instruction for author', :controller => "pages", :action => 'instruction_for_author'%></li>
</ul>

0.3.1/app/views/instructions/procedure.html.erb
<h1> Procedure of examination and publication </h1>
<blockquote>
	<p>Etiam vehicula, augue eu ultricies dictum, orci nisi suscipit sem, nec sollicitudin neque est ac massa. Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat. Nulla lobortis bibendum magna. Nulla adipiscing justo eu erat.</p>
	<p>Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat.</p>
</blockquote>

0.3.1/app/views/instructions/rules_of_edit.html.erb
<h1> Rules of edit </h1>
<blockquote>
	<p>Etiam vehicula, augue eu ultricies dictum, orci nisi suscipit sem, nec sollicitudin neque est ac massa. Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat. Nulla lobortis bibendum magna. Nulla adipiscing justo eu erat.</p>
	<p>Phasellus elementum nibh vel odio. Proin orci nulla, viverra tempus, pharetra ut, varius nec, justo. Donec euismod molestie erat.</p>
</blockquote>