0.3.1/config/routes.rb
Obri::Application.routes.draw do 
  devise_for :users do
  	match 'user' => "papers#index", :as => :user_root
  end
  resources :users

  get "home/index"

  resource :instructions do
    collection do
      get "index"
      get 'authorship'
      get "instruction_for_online_submission"
      get "instruction_for_author"
      get "rules_of_edit"
      get "procedure"
    end
  end
  
  resources :papers do
    collection do
      get 'all_paper'
      get 'review'
      get "filtered_for_editor"
      get 'authorship'
      get 'completed_paper'
    end
    member do
      get "make_comment"
      get 'confirm_submission'
      get "change_status"
      get 'result'
    end
  end
  
  resources :roles do
    collection do
      get "modify_role"
      get "all_user"
      get "manage_role"
      get "assignment"
    end
    member do
      get "change_role"
      get "make_assignment"
    end
  end

  
  root :to => "home#index"
  

  namespace :user do
    root :to => "home#index"
    resources :papers
    resources :papers do
      collection do
        get 'all_paper'
        get 'authorship'
        get 'review'
        get "filtered_for_editor"
        get 'completed_paper'
      end
      member do
        get "make_comment"
        get 'confirm_submission'
        get "change_status"
        get 'result'
      end
    end
    
    resources :roles do
      collection do
        get "modify_role"
        get "all_user"
        get "manage_role"
        get "assignment"
      end
      member do
        get "change_role"
        get "make_assignment"
      end
    end
        
        

    
  end
  

  

  

end

0.3.1/app/controllers/roles_controller.rb
class RolesController < ApplicationController
 # DB이름이 users여서 그런지 controller 이름을 users로 해주어야 정상작동.
  
  # 로그인 하지 않으면 볼수 없음. 특정 페이지로 바로 이동하면 이로그인 화면이 뜬다. 
  #before_filter :authenticate_user!
  before_filter :authenticate_user!
  
  #TODO : Administrator 만 관리 할 수 있게.

  def index    
  end
  
  def all_user
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end
  
  def change_role
    @user = User.find(params[:id])
    
    @user.role = params[:role]
    temp = @user.name
    
    @notice = "You assigned " + temp + " to the examiner"

    respond_to do |format|
      if @user.update_attributes(params[:id])
        format.html { redirect_to(all_user_roles_path, :notice => @notice) }
      else
        format.html { redirect_to(all_user_roles_path, :notice => 'You got an error, please retry.')} 
      end
    end    

  end
  
  def manage_role
    @users = User.all
    
    @examiners = Array.new
    @editors = Array.new
    
    @users.each do |user|
      if user.role.eql?('Reviewer')
        @examiners.push(user) 
      end
    end
  
    @users.each do |user|
      if user.role.eql?('Chiefeditor')
        @editors.push(user) 
      end
    end

  end
  
  def assignment
    @papers = Paper.all
    @users = User.all
    
    # examiner1,examiner2,examiner3 가 모두 채워지지 않은 경우에만 배정. 
    @unassigned = Array.new
    @assigned = Array.new
    
    # ㅋ컨펌 한 것아중 처음 보는 것들은 편집위원장으로 status 체인지.
    @papers.each do |p|
      if p.status.eql?("Submitted")
        p.status = "On chief editor"
        p.save
        # 작가에세 메일 스테이터스 변경 발송.
        #Emailer.send_status(p).deliver
      end
    end  
    
    @papers.each do |paper|
      if paper.status.eql?("On chief editor")
        @unassigned.push(paper) 
      elsif paper.status.eql?("Submitted")
        # 올페이퍼에서 안보고 바로오는 경우도 있다. 
        paper.status = "On chief editor"
        paper.save
        # 작가에세 메일 스테이터스 변경 발송.
        #Emailer.send_status(paper).deliver
        @unassigned.push(paper) 
      elsif paper.status.eql?("Peer review")
        @assigned.push(paper) 
      end
    end
    
    @temp = get_examiners
    @examiners = []
    
    @temp.each do |id, name|
      @examiners.push(id.to_s + '. '+name)
    end
 
  end
  
  def make_assignment
    @paper = Paper.find(params[:id])
    
    # 2번 배정이 없어야 실행. 
    unless params[:examiner1] == params[:examiner2] or params[:examiner1] == params[:examiner3] or params[:examiner2] == params[:examiner3]    
      @paper.examiner_name1 = params[:examiner1]
      @paper.examiner_name2 = params[:examiner2]
      @paper.examiner_name3 = params[:examiner3]
    
      # id로 이메일을 찾는다.
      @paper.examiner1 = User.find(params[:examiner1].split(".")[0]).email
      @paper.examiner2 = User.find(params[:examiner2].split(".")[0]).email
      @paper.examiner3 = User.find(params[:examiner3].split(".")[0]).email
    
      @paper.status = "Peer review"
      @paper.save
      
      title = 'OBRI ## You are assigned to reviewer : ' + @paper.title
      #리 리뷰어들에게 메일 보내는거 추가.
      Emailer.send_paper(@paper,  title, @paper.examiner1).deliver
      Emailer.send_paper(@paper,  title, @paper.examiner2).deliver
      Emailer.send_paper(@paper,  title, @paper.examiner3).deliver
      
      #Emailer.send_status(@paper).deliver   
    end
    
    @notice = params[:examiner1].split(".")[1].lstrip + ", " + params[:examiner2].split(".")[1].lstrip + "," + params[:examiner3].split(".")[1].lstrip + "  were assigned to paper as reviewer."
    respond_to do |format|
      if params[:examiner1] == params[:examiner2] or params[:examiner1] == params[:examiner3] or params[:examiner2] == params[:examiner3]
        format.html { redirect_to(assignment_roles_path, :notice => "One reviewer was assigned twice. Your assignment command didn't excute.") }
      elsif @paper.update_attributes(params[:id])
        format.html { redirect_to(assignment_roles_path, :notice => @notice) }
      else
        format.html { redirect_to(assignment_roles_path, :notice => 'You got an error, please retry.')}
      end     
    end
  end
  
  # id와 이름을  리턴.
  def get_examiners
    @users = User.all
    @examiners = Hash.new
    
    @users.each do |user|
      if user.role.eql?("Reviewer")
        @temp = { user.id => user.name }
        @examiners.merge!(@temp)
      end
    end
    
    return @examiners
  end
  
end

0.3.1/app/views/roles/all_user.html.erb
<h1>All users</h1>

<table CELLSPACING="10" CELLPADDING="5">
  <h3><tr> 
    <th>User ID</th>
	<th>Name</th>
	<th>Email</th>
    <th>Role</th>
	<th></th>
	<th></th>
	<th></th> 
	</tr></h3>
<% @users.each do |user| %>
  <tr>
	<td><%= user.id %></td>	
	<td><%= user.name %></td>
    <td><%= user.email %></td>
	<%= form_tag({:controller => "roles", :action => "change_role", :id => user}, :method => "get") do  %>
		<% if current_user.role.eql?("Administrator")%>
			<td><%= select_tag(:role , options_for_select(User::ROLES, user.role))  %></td>
		<% elsif current_user.role.eql?("Chiefeditor")%>
			<td><%= select_tag(:role , options_for_select(User::ROLES_FOR_EDITOR, user.role))  %></td>
		<% else %>
		<% end %>
		<td><%= submit_tag "Change role" %>
	<% end %>
  </tr>
<% end %>

</table>

0.3.1/app/views/roles/assignment.html.erb
<h1>Need to assign</h1>
<ul>
<li>Assign reviewers and click 'Assign' button</li>
<li>After assigned, you can't  change reviewer</li>
<li>Clicking 'Assign' button will take a couple of seconds, because it sends some mails.</li> 

</ul>
</br>
<% @unassigned.each do |paper| %>

<table  CELLSPACING="10" CELLPADDING="3" style="table-layout:fixed;" >
   <h3>
   <tr>
	<th width="400px" >Title</th>
	<th width="50px" >Name</th>
	<th width="100px" >Received</th>
	<th>Reviewer 1</th>	
	<th>Reviewer 2</th>	
	<th>Reviewer 3</th>	
	<th></th>
  	</tr>
	</h3>
	
  <tr>
	<td width="400px" style="word-break:break-all;"><%= paper.title %></td>
    <td><%= paper.last_name %><%= paper.first_name %></td>
	<td><%= paper.receive_time.strftime("%Y-%m-%d") %></td>
	<%= form_tag({:controller => "roles", :action => "make_assignment", :id => paper}, :method => "get") do  %>
		<td ><%= select_tag(:examiner1 , options_for_select(@examiners, paper.examiner_name1))  %></td>
		<td ><%= select_tag(:examiner2 , options_for_select(@examiners, paper.examiner_name2))  %></td>
		<td><%= select_tag(:examiner3 , options_for_select(@examiners, paper.examiner_name3))  %></td>
		<td ><%= submit_tag "Assign", :confirm =>"Are you sure?" %></td>
	<% end %>
  </tr>
</table>
	
<% end %>


<br><br>
<h1>Assigned</h1>
<table  CELLSPACING="10" CELLPADDING="3" style="table-layout:fixed;" >
  <tr>
	<th width="400px" >Title</th>
	<th width="50px" >Name</th>
	<th width="100px" >Received</th>
	<th width="100px" >Status</th>
	<th width="100px" >Reviewer1</th>
	<th width="100px" >Reviewer2</th>
	<th width="100px" >Reviewer3</th>
  </tr>
<% @assigned.each do |paper| %>
  <tr>
	<td width="400px" style="word-break:break-all;"><%= paper.title %></td>
    <td><%= paper.last_name %><%= paper.first_name %></td>
	<td><%= paper.receive_time.strftime("%Y-%m-%d") %></td>
	<td><%= paper.status%></td>
	<td><%= paper.examiner_name1.split(".")[1].lstrip  %></td>
	<td><%= paper.examiner_name2.split(".")[1].lstrip  %></td>
	<td><%= paper.examiner_name3.split(".")[1].lstrip  %></td>	
  </tr>
<% end %>
</table>

0.3.1/app/views/roles/index.html.erb
<h1>Manage users</h1>

	<ul>
	<li><%= link_to 'All users & change role', all_user_roles_path %></li>
	<li><%= link_to 'View members of role group', manage_role_roles_path %></li>
	<li><%= link_to 'Assign examiners to paper', assignment_roles_path %></li>	
	</ul>

0.3.1/app/views/roles/manage_role.html.erb
<p id="notice"><%= notice %></p>

<h3>Chief editor</h3>

<table CELLSPACING="10" CELLPADDING="5">
  <tr> 
  <h4>
    <th>User ID</th>
	<th>Name</th>
	<th>Email</th>
	<th></th>
  </h4>
	</tr>
<% @editors.each do |editor| %>
  <tr>
	<td><%= editor.id %></td>	
	<td><%= editor.name %></td>
    <td><%= editor.email %></td>
  </tr>
<% end %>

</table>
<br/><br/>
<h3>Examiner </h3>

<table CELLSPACING="10" CELLPADDING="5">
  <tr> 
  <h4>
    <th>User ID</th>
	<th>Name</th>
	<th>Email</th>
	<th></th>
  </h4>
	</tr>
<% @examiners.each do |examiner| %>
  <tr>
	<td><%= examiner.id %></td>	
	<td><%= examiner.name %></td>
    <td><%= examiner.email %></td>
  </tr>
<% end %>

</table>